export const SET_DRAFT_POST = "SET_DRAFT_POST";
export const CREATING_POST_FAIL = "CREATING_POST_FAIL";
export const IS_ALERT_SHOW = "IS_ALERT_SHOW";
export const SET_IS_ADMIN = "SET_IS_ADMIN";

export const SET_UPDATE_FB_TOKEN = "SET_UPDATE_FB_TOKEN";
export const SET_ALL_USER_FCM = "SET_ALL_USER_FCM";
export const SET_PUSH_NOTI = "SET_PUSH_NOTI";
export const SET_SHOW_SPLASH = "SET_SHOW_SPLASH";
export const SET_IS_UN_READED = "SET_IS_UN_READED";
export const SET_CATEGORIES_LIST = "SET_CATEGORIES_LIST";
export const SET_APP_LOADER = "SET_APP_LOADER";
